### ISSUE TITLE
package-level mocha using ts-node does not work

### ISSUE THREAD

**Issue by mschnee** [mschnee/mister#8]
From within a package folder:
```
..\..\..\node_modules\.bin\mocha --require ts-node/register
```

```
Warning: Could not find any test files matching pattern: test/fixtures/**/*.spec.ts
C:\path\to
monorepo-project\packages\node_modules\re-store\src\Store\__tests__\registerReducer.spec.ts:2
import { expect } from 'chai';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\path\to
    monorepo-project\node_modules\ts-node\src\index.ts:431:14)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\path\to
    monorepo-project\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\path\to
    monorepo-project\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\path\to
    monorepo-project\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\path\to
    monorepo-project\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

Things to test:
- [ ] Write tests in javascript.  Does `mocha` work correctly?
- [ ] Same with `nyc mocha`.
- [ ] Attempt to do a local install of `ts-node` (only, no `typescript`, `mocha`, or `nyc`)

These steps are to isolate which dependency is de-pathing.

**Comment by mschnee** [comment]
Upon further investigation, ts-node may ignore `/node_modules/`.  If that's a regex and not a gitignore-style string, it could mean `./node_modules` and `./packages/node_modules/` are both ignored.  If so, find a good configuration for ts-node and document it.

**Comment by mschnee** [comment]
```js
"test": "cross-env TS_NODE_IGNORE=\"/(?<!packages\/)node_modules/\" nyc mocha",
```
